# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
  
pool:  
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: DotNetCoreCLI@2
  name: Restoring
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: Building
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  name: Testing
  inputs:  
    command: 'test'

- task: DotNetCoreCLI@2
  name: Packing
  inputs:    
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
