# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
  
pool:
  # vmImage: 'windows-latest'
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: Restore packages
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: Building
  inputs:
    command: 'build'

- task: Tests
  inputs:
    command: 'test'

- task: Packing
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
